### ISSUE TITLE
CHEBI: 87560 Cross Double Bond 

### ISSUE THREAD

**Issue by theArsalanM** [chembl/libRDChEBI#6]
Current ChEBI:
https://www.ebi.ac.uk/chebi/displayImage.do?defaultImage=true&imageIndex=0&chebiId=87560&dimensions=600

ChEBI 2.0:
https://wwwdev.ebi.ac.uk/chebi/beta/api/media/svg/2889846.svg

**Comment by eloyfelix** [comment]
pasting images in case the links stop working at any point. We need to investigate this

current:
![curr](https://github.com/chembl/libRDChEBI/assets/1122541/de789503-e369-44a0-bd82-f1676f594e64)

new:
<img width="298" alt="Screenshot 2023-10-31 at 11 01 02" src="https://github.com/chembl/libRDChEBI/assets/1122541/7b2f5f1f-b149-467e-84c8-85d78698c44a">

**Comment by eloyfelix** [comment]
There might be something wrong with the stereochemistry of the structure. RDKit and CDK by default remove the dashed/wedged hidrogen (it shows wedged in the main view but it gets dashed in the zoom).

Our logic does something a bit weird because it keeps the hidrogen but removes the dash/wedge and crosses the bond because it probably finds something is odd with the molecule.

Inchi binary throws a warning:

<img width="375" alt="Screenshot 2024-02-13 at 13 53 20" src="https://github.com/chembl/libRDChEBI/assets/1122541/7de380d2-05f2-4ad8-89bb-7856f206119b">

pubchem is showing this:
<img width="942" alt="Screenshot 2024-02-13 at 14 00 05" src="https://github.com/chembl/libRDChEBI/assets/1122541/fc26684d-88b6-4922-a81e-4e0787c2c1fa">

@amalik01, can you take a look at it?

**Comment by amalik01** [comment]
Double bonds that have undefined stereochemistry are drawn using wavy/wiggly bonds. These wiggly bonds are recommended by IUPAC hence the structure shown in the current ChEBI is correct. The wiggly bond appears like a wedged bond since the structure is small. When the structure is zoomed in, it is clear that it is a wiggly bond.

However, many structure editors use crossed-double bonds to depict undefined stereochemistry (Even ChEMBL adopts crossed-double bonds). Unfortunately, these are not recommended by IUPAC since it is not clear from the image whether a crossed-double bond means undefined or a mixture of both isomers (E/Z-forms). We don't use crossed-double bonds in ChEBI so this needs to be fixed.

**Comment by eloyfelix** [comment]
thanks @amalik01. The "dash" I was seeing confused me a bit. That can be fixed.

**Comment by eloyfelix** [comment]
fixed here: https://github.com/chembl/libRDChEBI/commit/c7bb643b7cf2875d6633c1a937c23024aa7583ac

@theArsalanM @CarMoreno please update the version of librdchebi to 0.2.2
